eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6001/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: GestionUtilisateur
          uri: lb://GestionUtilisateur
          predicates:
            - Path=/utilisateur/**
          filters:
            - RewritePath=/utilisateur/(?<path>.*), /$\{path}
        
        - id: GestionAbonnement
          uri: lb://GestionAbonnement
          predicates:
            - Path=/abonnement/**
          filters:
            - RewritePath=/abonnement/(?<path>.*), /$\{path}
